# Not recommend...FOR DEMO PURPOSES!
on: push

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
    - run: |
        import os
        print(len(os.getenv('MY_VAR')))
        print(os.getenv('MY_VAR'))
      shell: python
    env:
      MY_VAR: $${{ secrets.MY_DEMO_SECRET }}
